In [1]:
import numpy as np

# 1. Convert 1D array to 2D
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr1d.reshape(2, 3)
print("1D to 2D Array:\n", arr2d)

# 2. Print Array Attributes
print("\nArray Attributes:")
print("Shape:", arr2d.shape)
print("Dimension:", arr2d.ndim)
print("Data Type:", arr2d.dtype)
print("Item Size:", arr2d.itemsize)

# 3. Create a 3x3 NumPy array of all 9
arr = np.full((3, 3), 9)
print("\n3x3 Array of 9:")
print(arr)

# 4. Create a 1D array of 10 evenly spaced values between 25 and 125
arr = np.linspace(25, 125, 10)
print("\nEvenly Spaced Values:")
print(arr)

# 5. Convert a Python list into a NumPy array
lst = [10, 20, 30, 40]
arr = np.array(lst)
print("\nList to NumPy Array:")
print(arr)

# 6. Reverse a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
rev = arr[::-1]
print("\nReversed Array:")
print(rev)

# 7. Create a 4x4x3 array and extract value at second set, first row and last column
arr = np.arange(48).reshape(4, 4, 3)
print("\n4x4x3 Array:")
print(arr)
print("\nSecond Set, First Row, Last Column:")
print(arr[1, 0, 2])

# 8. Create a 4x4 and Extract Odd Rows and Even Columns
arr = np.arange(1, 17).reshape(4, 4)
print("\n4x4 Array:")
print(arr)
print("\nOdd Rows and Even Columns:")
print(arr[::2, 1::2])

# 9. Slice first two rows and first two columns of second set from 4x4x3 array
print("\nFirst 2 Rows and First 2 Columns of Second Set:")
print(arr.reshape(4,4,1))  # ignore if using separate array

arr3d = np.arange(48).reshape(4,4,3)
print(arr3d[1, :2, :2])

# 10. Replace odd numbers with -1 using for loop
arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1

print("\nOdd Numbers Replaced with -1:")
print(arr)

# 11. Get indices of non-zero elements
arr = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr)
print("\nIndices of Non-Zero Elements:")
print(indices)

# 12. Arithmetic Operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("\nAddition:")
print(arr1 + arr2)

print("\nMultiplication:")
print(arr1 * arr2)

# 13. Dot Product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)

print("\nDot Product:")
print(dot_product)

1D to 2D Array:
 [[1 2 3]
 [4 5 6]]

Array Attributes:
Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8

3x3 Array of 9:
[[9 9 9]
 [9 9 9]
 [9 9 9]]

Evenly Spaced Values:
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]

List to NumPy Array:
[10 20 30 40]

Reversed Array:
[5 4 3 2 1]

4x4x3 Array:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Second Set, First Row, Last Column:
14

4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]

First 2 Rows and First 2 Columns of Second Set:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]]
[[12 13]
 [15 16]]

Odd Numbers Replaced with -1:
[[-1 56 78 -1